//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

pub use super::follow_relations::Entity as FollowRelations;
pub use super::sessions::Entity as Sessions;
pub use super::user_tweets::Entity as UserTweets;
pub use super::users::Entity as Users;
