version: '3.8'

services:
    app:
        volumes:
            - ./app:/app/
        working_dir: /app
        tty: true
        build:
            context: ./app
            dockerfile: Dockerfile.local
        ports:
            - 3000:3000
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres
            - POSTGRES_HOST=postgres
            - POSTGRES_PORT=5432
        command: sh -c 'go mod tidy && air'
    front:
        image: node:18-bullseye-slim
        working_dir: /app
        ports:
            - 5173:5173
        volumes:
            - ./front:/app/
        command:
            - /bin/bash
            - -c
            - |
                npm install
                npm run dev -- --host

    postgres:
        image: postgres:16-alpine3.18
        ports:
            - '5432:5432'
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres
        volumes:
            - ./data:/var/lib/postgresql/data
            - ./init:/docker-entrypoint-initdb.d
